name: ci-test

on:
  push:
    branches: [ "dev","master" ]
  pull_request:
    branches: [ "dev" ,"master"]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test
